# Generated by Django 4.0.4 on 2022-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createDevocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teme', models.CharField(default='Tema', max_length=30)),
                ('verse', models.TextField(default='Jesus chorou.')),
                ('reference', models.CharField(default='João 11:35', max_length=50)),
                ('text', models.TextField(default='Jesus nos ama')),
            ],
        ),
    ]
