# Generated by Django 4.0.4 on 2022-07-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdevocional',
            old_name='teme',
            new_name='theme',
        ),
    ]
