# Generated by Django 4.0.4 on 2022-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_rename_teme_createdevocional_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdevocional',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2000-12-30'),
            preserve_default=False,
        ),
    ]
