# Generated by Django 4.0.4 on 2022-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdevocional',
            name='theme',
            field=models.CharField(default='Tema', max_length=35),
        ),
    ]
