# Generated by Django 4.0.4 on 2022-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_createdevocional_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdevocional',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='%m'),
        ),
    ]
